### PR TITLE
Align linux64 performance tweak to freedom_metal

### PR DESCRIPTION
**Pull request by reclusejack**

### CODE REVIEW

**Review by bsousi5 — COMMENTED** [review]
You should also update the PORT_FLAGS to have the same compiler options to reflect the scores send out in the status.
Also remove the nano.spec, since freedom-e-sdk already default to use nano.spec

**Comment by reclusejack** [comment]
Got, I will update the patch~

**Comment by reclusejack** [comment]
@bsousi5 , We want to move the optimization flags from coremark to freedom-e-sdk because the options are core dependent. I've pushed the patch to sifive-coremark branch. Please let me know what you think.
https://github.com/sifive/freedom-e-sdk/commit/e746d6e0c3ca041b0c811d77d8be65acbe33362d

**Review by bsousi5 — APPROVED** [review]
LGTM

**Pull request merged**
